enable-module-update = true # set this to false if you do not want to receive updates for the module
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
enabled = false # Disables the standard ReVanced build to prevent 404 API conflicts

[YouTube-Morphe]
enabled = true
app-name = "YouTube"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[Music-Morphe]
enabled = true
app-name = "Music"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
build-mode = "both"
arch = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"

[Telegram]
enabled = true
package = "org.telegram.messenger"
patches-source = "paresh-patches"
rv-brand = "Morphe"
version = "auto"

[Brave]
enabled = true
package = "com.brave.browser"
patches-source = "bufferk"
rv-brand = "Morphe"
version = "auto"

[Prime-Video]
enabled = true
package = "com.amazon.avod.thirdpartyclient"
patches-source = "Android TV" # Note: Most Morphe Prime Video patches target the Android TV version
rv-brand = "Morphe"
version = "auto"

[JioHotstar]
enabled = true
package = "in.startv.hotstar"
patches-source = "durgesh0505/chiggi_morphe_patches"
rv-brand = "Morphe"
version = "auto"

[Amazon-Shopping]
enabled = true
package = "com.amazon.mShop.android.shopping"
patches-source = "rushiranpise"
rv-brand = "Morphe"
version = "auto"

[Cloudflare-1.1.1.1]
enabled = true
package = "com.cloudflare.onedotonedotonedotone"
patches-source = "rushiranpise"
rv-brand = "Morphe"
version = "auto"

[Adobe-Acrobat]
enabled = true
package = "com.adobe.reader"
patches-source = "hoomans-patches"
rv-brand = "Morphe"
version = "auto"

[Duolingo]
enabled = true
package = "com.duolingo"
patches-source = "hoo-dles"
rv-brand = "Morphe"
version = "auto"

[Reddit]
enabled = true
package = "com.reddit.frontpage"
patches-source = "MorpheApp/morphe-patches" # Default Morphe patches
rv-brand = "Morphe"
version = "auto"

[CamScanner]
enabled = true
package = "com.intsig.camscanner"
patches-source = "hoo-dles"
rv-brand = "Morphe"
version = "auto"

